#!/bin/bash

# Generate command for mounting the project NFS store. We bake the output into
# nfs_mount_cmd.sh so that we don't have to install the Google Cloud SDK on our
# Ray worker nodes (which would require some annoying credential distribution
# steps).

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${THIS_DIR}/nfs_config.sh"

echo "Inferring IP address of server '$SERVER_NAME' (zone '$ZONE')"
server_ip="$(get_server_ip)"
if [ -z "$server_ip" ]; then
    echo "Could not read server IP from 'gcloud filestore instances describe'. "\
        "Do the server ('$SERVER_NAME') and zone ('$ZONE') values make sense?"
    exit 1
fi

echo -e "Got IP '$server_ip'. Here is the generated script:\n\n"
echo "vvvvvvvvvv (output file) vvvvvvvvvv"
tee "${THIS_DIR}/nfs_mount.sh" <<EOF
#!/bin/bash
# SCRIPT AUTOGENERATED BY $(basename "$0"); DO NOT EDIT MANUALLY

# This is a script to mount the il-representations project filesystem from
# server '$SERVER_NAME' (zone '$ZONE'). It will only work on GCP.

set -e

if [ -z "\$(cat /proc/filesystems | grep 'nfsd\$')" ]; then
    echo "This machine does not seem to have NFS support. Will attempt to"\\
        "install NFS packages."
    apt-get update -y && apt-get install -y nfs-common
fi

mkdir -p '$CLIENT_MOUNT_POINT' \\
    && mount '$server_ip:/vol1' '$CLIENT_MOUNT_POINT'

echo "Done! Mount should be accessible on '$CLIENT_MOUNT_POINT'"
EOF
echo "^^^^^^^^^^ (output file) ^^^^^^^^^^"
