version: 2.1

jobs:
  build-and-test:
    docker:
      - image: qxcv/il-representations:2020.08.03-r2
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: Install dependencies
      - run:
          command: pip install -e .
          name: Install in dev mode
      - run:
          command: xvfb-run -a pytest tests/
          name: Run Tests

workflows:
  main:
    jobs:
      - build-and-test
