version: 2.1

jobs:
  build-and-test:
    docker:
      - image: humancompatibleai/il-representations:2020.09.14-r1
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: Install dependencies
      - run:
          command: curl -so ~/.mujoco/mjkey.txt "${MUJOCO_KEY}"
          name: Set up MuJoCo
      - run:
          command: pip install -e .
          name: Install in dev mode
      - run:
          command: |
            mkdir -p test-results
            xvfb-run -a pytest --junitxml=test-results/junit.xml tests/
          name: Run Tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - build-and-test:
          context: MuJoCo
