version: 2.1

jobs:
  build-and-test:
    resource_class: large
    docker:
      # this is also used in gcp_cluster_template.yaml (if you change this file,
      # remember to update all your cluster configs too)
      - image: "humancompatibleai/il-representations:2021.10.30-r1"
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: Install dependencies
      - run:
          command: curl -so ~/.mujoco/mjkey.txt "${MUJOCO_KEY}"
          name: Set up MuJoCo
      - run:
          command: pip install -e .
          name: Install in dev mode
      - run:
          command: |
            mkdir -p test-results
            xvfb-run -a pytest --junitxml=test-results/junit.xml tests/
          name: Run Tests
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - build-and-test:
          context: MuJoCo
